---
sidebar: sidebar 
permalink: ontap-select-cisco-unified-edge/ontap-select-cisco-unified-edge-deployment-methodology.html 
keywords: ontap select, cisco unified edge, deployment, methodology, flexpod 
summary: Descreve as etapas de alto nível para licenciamento, dimensionamento, configuração de storage local e implantação do ONTAP Select no Cisco Unified Edge. 
---
= Metodologia de implantação de alto nível
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Esta seção descreve as etapas de alto nível para licenciamento, dimensionamento, configuração de storage local e implantação do ONTAP Select no Cisco Unified Edge.



[[1-ontap-select-licensing]]
== 1. Licenciamento do ONTAP Select

É necessária uma licença Premium XL ao usar unidades NVMe. Os clientes podem escolher entre uma licença de pool de capacidade flexível, que compartilha a capacidade entre vários sites, e uma licença perpétua vinculada a um nó específico. Consulte link:https://docs.netapp.com/us-en/ontap-select/concept_lic_workflow.html["Fluxo de trabalho de compra de licenças para o ONTAP Select"] para obter mais detalhes.



[[2-obtain-ontap-select-deploy-software]]
== 2. Obtenha o software ONTAP Select Deploy

O ONTAP Select Deploy é o utilitário de administração usado para implantar e gerenciar clusters ONTAP Select. O Deploy é distribuído como uma máquina virtual Linux que você deve instalar antes de criar um cluster ONTAP Select. Ele pode ser instalado a partir de link:https://stackautomation.cisco.com/["Automação de Cisco Stack"] ou baixado como um arquivo .ova do link:https://mysupport.netapp.com/site/["NetApp site de suporte"].



[[3-choose-ontap-select-virtual-machine-size]]
== 3. Escolha o tamanho da máquina virtual ONTAP Select

O ONTAP Select com licença Premium XL pode ser implementado como instâncias de máquina virtual de tamanho pequeno, médio ou grande para atender aos requisitos de desempenho de storage. Os nós de computação XE130c ou XE150c com 12 núcleos podem suportar instâncias de tamanho pequeno ou médio, enquanto nós com 20 ou 32 núcleos são necessários para instâncias grandes. Consulte link:https://docs.netapp.com/us-en/ontap-select/reference_plan_ots_hardware.html#basic-hardware-requirements["ONTAP Select considerações sobre hipervisor VMware e hardware"] para obter detalhes adicionais sobre os requisitos de dimensionamento de instâncias.



[[4-prepare-local-storage]]
== 4. Prepare o storage local

O recurso VMDirectPath I/O Pass-through é usado nas unidades NVMe para maximizar a eficiência. Essa configuração expõe as unidades à máquina virtual, permitindo que o ONTAP tenha acesso PCI direto ao dispositivo. Consulte link:https://docs.netapp.com/us-en/ontap-select/task_chk_nvme_configure.html["Configurar um host ONTAP Select para usar unidades NVMe"] para obter detalhes sobre como habilitar o NVMe pass-through.

Uma das quatro unidades NVMe é usada como disco de sistema, contendo a unidade de inicialização da máquina virtual, o núcleo e a NVRAM. As três unidades restantes são configuradas como discos de dados com RAID 4 por software para fornecer proteção baseada em paridade contra falhas individuais de unidade. Cada disco de dados é dividido em três partições: uma pequena partição raiz e duas partições de tamanho igual para criar dois discos de dados visíveis na máquina virtual do ONTAP Select. Consulte link:https://docs.netapp.com/us-en/ontap-select/concept_stor_swraid_local.html#ontap-select-virtual-and-physical-disks["Serviços de configuração de RAID de software ONTAP Select para storage conectado localmente"] para obter mais detalhes.

O disco do sistema pode ter uma capacidade de storage menor do que a dos três discos de dados para reduzir os custos gerais de storage da solução. Uma unidade de 1,6 TB de alto desempenho e alta resistência (UCSXE-NVE11T6K1P) é suficiente.



[[5-deploy-the-ontap-select-instance]]
== 5. Implante a instância do ONTAP Select

O ONTAP Select é implementado como uma máquina virtual usando a ferramenta ONTAP Select Deploy e o ambiente de hipervisor compatível. Durante a implementação, o administrador define o nó, as interfaces de gerenciamento, as interfaces de dados, a capacidade e as atribuições de disco local. Após o ONTAP Select estar em execução, os administradores devem criar volumes ou LUNs para os aplicativos locais e aplicar as políticas, compartilhamentos, grupos de iniciadores ou controles de acesso apropriados.
