---
sidebar: sidebar 
permalink: express/express-c-series-c190-deploy_netapp_aff_storage_deployment_procedure_@part_2@.html 
keywords: aff, storage, deployment, procedure, create, iscsi, igroups, ontap, san, boot 
summary: Para criar grupos, execute os seguintes comandos a partir da conexão SSH do nó de gerenciamento de cluster. 
---
= Procedimento de implantação de storage do NetApp AFF (parte 2)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/




== Configurar o armazenamento de arranque SAN ONTAP



=== Criar grupos iSCSI


NOTE: Você precisa do iniciador iSCSI IQNs da configuração do servidor para esta etapa.

Para criar grupos, execute os seguintes comandos a partir da conexão SSH do nó de gerenciamento de cluster. Para ver os três grupos criados nesta etapa, execute o `igroup show` comando.

....
igroup create –vserver Infra-SVM –igroup VM-Host-Infra-A –protocol iscsi –ostype vmware –initiator <<var_vm_host_infra_a_iSCSI-A_vNIC_IQN>>,<<var_vm_host_infra_a_iSCSI-B_vNIC_IQN>>
igroup create –vserver Infra-SVM –igroup VM-Host-Infra-B –protocol iscsi –ostype vmware –initiator <<var_vm_host_infra_b_iSCSI-A_vNIC_IQN>>,<<var_vm_host_infra_b_iSCSI-B_vNIC_IQN>>
....

NOTE: Esta etapa deve ser concluída ao adicionar servidores Cisco UCS C-Series adicionais.



== Mapeie LUNs de inicialização para grupos

....
To map boot LUNs to igroups, run the following commands from the cluster management SSH connection:
lun map –vserver Infra-SVM –volume esxi_boot –lun VM-Host-Infra-A –igroup VM-Host-Infra-A –lun-id 0
lun map –vserver Infra-SVM –volume esxi_boot –lun VM-Host-Infra-B –igroup VM-Host-Infra-B –lun-id 0
....

NOTE: Esta etapa deve ser concluída ao adicionar servidores Cisco UCS C-Series adicionais.

link:express-c-series-c190-deploy_vmware_vsphere_6.7u2_deployment_procedure.html["Próximo: Procedimento de implantação do VMware vSphere 6.7U2."]
