---
sidebar: sidebar 
permalink: express/express-c-series-c190-deploy_program_summary_overview.html 
keywords: fexpod, express, cisco, ucs, series, c, aff, c190, nva, deployment 
summary: O data center FlexPod e o FlexPod Express oferecem uma configuração de linha de base e têm a flexibilidade de ser dimensionados e otimizados para acomodar vários casos de uso e requisitos diferentes. 
---
= NVA-1142-DEPLOY: FlexPod Express com Cisco UCS C-Series e NetApp AFF C190 Series - implantação NVA
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Saraiva, NetApp

[role="lead"]
As tendências do setor indicam que uma grande transformação do data center está ocorrendo em relação à infraestrutura compartilhada e à computação em nuvem. Além disso, as organizações buscam uma solução simples e eficaz para escritórios remotos e filiais que usem a tecnologia que já conhecem em seu data center.

O FlexPod Express é uma arquitetura de data center pré-projetada e de práticas recomendadas, desenvolvida com base no sistema de computação unificada da Cisco (Cisco UCS), na família de switches Cisco Nexus e nas tecnologias de armazenamento NetApp. Os componentes de um sistema FlexPod Express são como os seus homólogos do data center FlexPod, permitindo sinergias de gerenciamento em todo o ambiente de INFRAESTRUTURA DE TI em menor escala. O data center FlexPod e o FlexPod Express são plataformas ideais para virtualização e para sistemas operacionais bare-metal e workloads empresariais.

O data center FlexPod e o FlexPod Express oferecem uma configuração de linha de base e têm a flexibilidade de ser dimensionados e otimizados para acomodar vários casos de uso e requisitos diferentes. Os clientes de data center FlexPod existentes podem gerenciar o sistema FlexPod Express com as ferramentas às quais estão acostumados. Os novos clientes do FlexPod Express podem fazer a transição para o gerenciamento do data center FlexPod à medida que seu ambiente cresce.

O FlexPod Express é uma base ideal de infraestrutura para escritórios remotos e filiais e para empresas de pequeno e médio porte. Ele também é uma solução ideal para clientes que desejam fornecer infraestrutura para um workload dedicado.

O FlexPod Express fornece uma infraestrutura fácil de gerenciar, adequada para praticamente qualquer workload.
