---
sidebar: sidebar 
permalink: express/express-c-series-c190-deploy_deployment_procedures_overview.html 
keywords: configure,  express, flexpod, cisco, series, c190, deployment, overview 
summary: Este documento fornece detalhes para configurar um sistema FlexPod Express totalmente redundante e altamente disponível. Para refletir essa redundância, os componentes que estão sendo configurados em cada etapa são referidos como componente A ou componente B. 
---
= Visão geral
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Este documento fornece detalhes para configurar um sistema FlexPod Express totalmente redundante e altamente disponível. Para refletir essa redundância, os componentes que estão sendo configurados em cada etapa são referidos como componente A ou componente B. por exemplo, controlador A e controlador B identificam os dois controladores de storage NetApp que são provisionados neste documento. O switch A e o switch B identificam um par de switches Cisco Nexus.

Além disso, este documento descreve etapas para provisionar vários hosts Cisco UCS, que são identificados sequencialmente como servidor A, servidor B e assim por diante.

Para indicar que você deve incluir informações pertinentes ao seu ambiente em uma etapa, `\<<text>>` aparece como parte da estrutura de comando. Veja o exemplo a seguir para o `vlan create` comando:

....
Controller01> network port vlan create –node <<var_nodeA>> -vlan-name <<var_vlan-name>>
....
Este documento permite configurar totalmente o ambiente do FlexPod Express. Nesse processo, várias etapas exigem que você insira convenções de nomenclatura específicas do cliente, endereços IP e esquemas de rede local virtual (VLAN). A tabela a seguir descreve as VLANs necessárias para implantação, conforme descrito neste guia. Esta tabela pode ser concluída com base nas variáveis específicas do site e usada para implementar as etapas de configuração do documento.


NOTE: Se você usar VLANs separadas de gerenciamento dentro e fora da banda, será necessário criar uma rota de camada 3 entre elas. Para essa validação, uma VLAN de gerenciamento comum foi usada.

|===
| Nome da VLAN | Finalidade do VLAN | ID DA VLAN |  


| VLAN de gerenciamento | VLAN para interfaces de gerenciamento | 3437 | vSwitch0 


| VLAN NFS | VLAN para tráfego NFS | 3438 | vSwitch0 


| VLAN do VMware vMotion | VLAN designada para o movimento de máquinas virtuais (VMs) de um host físico para outro | 3441 | vSwitch0 


| VLAN de tráfego de VM | VLAN para tráfego de aplicação de VM | 3442 | vSwitch0 


| ISCSI-A-VLAN | VLAN para tráfego iSCSI na malha A | 3439 | IScsiBootvSwitch 


| ISCSI-B-VLAN | VLAN para tráfego iSCSI na malha B | 3440 | IScsiBootvSwitch 


| VLAN nativo | VLAN à qual os quadros não marcados são atribuídos | 2 |  
|===
Os números de VLAN são necessários durante toda a configuração do FlexPod Express. As VLANs são referidas como `\<<var_xxxx_vlan>>`, onde `xxxx` é a finalidade da VLAN (como iSCSI-A).

Existem dois vSwitches criados nesta validação.

A tabela a seguir lista os vSwitches da solução.

|===
| Nome do vSwitch | Adaptadores ativos | Portas | MTU | Balanceamento de carga 


| vSwitch0 | Vmnic2, vmnic4 | padrão (120) | 9000 | Rota baseada em hash IP 


| IScsiBootvSwitch | Vmnic3, vmnic5 | padrão (120) | 9000 | Rota com base no ID de porta virtual de origem. 
|===

NOTE: O método de hash IP de balanceamento de carga requer uma configuração adequada para o switch físico subjacente usando SRC-DST-IP EtherChannel com um canal de porta estático (modo ligado). Em caso de conetividade intermitente devido a uma possível configuração incorreta do switch, desligue temporariamente uma das duas portas de uplink associadas no switch Cisco para restaurar a comunicação com a porta vmkernel de gerenciamento ESXi enquanto soluciona problemas de configurações do canal de porta.

A tabela a seguir lista as VMs VMware criadas.

|===
| Descrição da VM | Nome do host 


| VMware vCenter Server | FlexPod-VCSA 


| Console de armazenamento virtual | FlexPod-VSC 
|===