---
sidebar: sidebar 
permalink: express/express-c-series-c190-deploy_technology_requirements.html 
keywords: technology, requirements, hardware, software, express, c, series, deployment 
summary: Um sistema FlexPod Express requer uma combinação de componentes de hardware e software. O FlexPod Express também descreve os componentes de hardware necessários para adicionar nós de hipervisor ao sistema em unidades de dois. 
---
= Requisitos de tecnologia
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Um sistema FlexPod Express requer uma combinação de componentes de hardware e software. O FlexPod Express também descreve os componentes de hardware necessários para adicionar nós de hipervisor ao sistema em unidades de dois.



== Requisitos de hardware

Independentemente do hypervisor escolhido, todas as configurações do FlexPod Express usam o mesmo hardware. Portanto, mesmo que os requisitos de negócios mudem, você pode usar um hypervisor diferente no mesmo hardware do FlexPod Express.

A tabela a seguir lista os componentes de hardware necessários para a configuração e implementação do FlexPod Express. Os componentes de hardware usados em qualquer implementação da solução podem variar de acordo com os requisitos do cliente.

|===
| Hardware | Quantidade 


| Cluster de dois nós do AFF C190 | 1 


| Servidor Cisco C220 M5 | 2 


| Switch Cisco Nexus 31108PC-V. | 2 


| Placa de interface virtual (VIC) Cisco UCS 1457 para servidor de rack Cisco UCS C220 M5 | 2 
|===
Esta tabela lista o hardware necessário, além da configuração base para a implementação do 10GbE.

|===
| Hardware | Quantidade 


| Servidor Cisco UCS C220 M5 | 2 


| Cisco VIC 1457 | 2 
|===


== Requisitos de software

A tabela a seguir lista os componentes de software necessários para implementar as arquiteturas das soluções FlexPod Express.

|===
| Software | Versão | Detalhes 


| Controlador de gerenciamento integrado Cisco (CIMC) | 4.0.4 | Para servidores de rack Cisco UCS C220 M5 


| Cisco nenic driver | 1.0.0.29 | Para placas de interface VIC 1457 


| Cisco NX-os | 7,0 (3)I7 (6) | Para switches Cisco Nexus 31108PC-V. 


| NetApp ONTAP | 9,6 | Para controladores AFF C190 
|===
Esta tabela lista o software necessário para todas as implementações do VMware vSphere no FlexPod Express.

|===
| Software | Versão 


| Dispositivo de servidor VMware vCenter | 6.7U2 


| Hipervisor VMware vSphere ESXi | 6.7U2 


| Plug-in NetApp VAAI para ESXi | 1.1.2 


| NetApp VSC | 9,6 
|===