---
sidebar: sidebar 
permalink: fp-def/dc-tech-spec_cisco_nexus_switching_modes_of_operation.html 
keywords: cisco, nexus, nx-os, aci, switching, modes, operation, datacenter, technical, specifications 
summary: Uma variedade de produtos Cisco Nexus pode ser usada como o componente de comutação em uma determinada FlexPod deployment. A maioria dessas opções utiliza o software Cisco NX-OS. A família Cisco Nexus de switches oferece diferentes capacidades em suas linhas de produtos. Essas capacidades são detalhadas posteriormente neste documento. 
---
= Modos de comutação Cisco Nexus de operação
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Uma variedade de produtos Cisco Nexus pode ser usada como o componente de comutação em uma determinada FlexPod deployment. A maioria dessas opções utiliza o software Cisco NX-OS. A família Cisco Nexus de switches oferece diferentes capacidades em suas linhas de produtos. Essas capacidades são detalhadas posteriormente neste documento.

A oferta da Cisco no espaço de rede definida por software é chamada de Application Centric Infrastructure (ACI). A linha de produtos Cisco Nexus que suporta o modo ACI (modo fabric) também pode ser implementada no modo NX-OS.

O Cisco ACI destina-se a implantações de data center que se concentram nos requisitos de uma aplicação específica. Os aplicativos são instanciados por meio de uma série de perfis e contratos que permitem a conetividade do host ou da máquina virtual (VM) até o armazenamento.

O FlexPod Datacenter é validado com ambos os modos de operação dos switches Cisco Nexus. Para obter mais informações sobre os modos ACI e NX-OS, consulte as seguintes páginas da Cisco:

* http://www.cisco.com/c/en/us/solutions/data-center-virtualization/application-centric-infrastructure/index.html["Infraestrutura centrada em aplicações da Cisco"^]
* https://www.cisco.com/site/us/en/products/networking/cloud-networking/nx-os/index.html["Software Cisco NX-os"^]

