---
sidebar: sidebar 
permalink: fp-def/dc-tech-spec_supported_versus_validated_flexpod_configurations.html 
keywords: flexpod, architecture, supported, validated, configurations, hardware, software 
summary: A arquitetura FlexPod é definida pelo conjunto de regras descritas neste documento. 
---
= Configurações de FlexPod validadas em comparação com compatíveis
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
A arquitetura FlexPod é definida pelo conjunto de regras descritas neste documento. Os componentes de hardware e as configurações de software devem ser suportados pelo https://ucshcltool.cloudapps.cisco.com/public/["Lista de compatibilidade de hardware e software do Cisco UCS"^] e pelo http://mysupport.netapp.com/matrix["Ferramenta de Matriz de interoperabilidade NetApp (IMT)"^].

Cada Cisco Validated Design (CVD) ou NetApp Verified Architecture (NVA) é uma possível configuração de FlexPod. O Cisco e o NetApp documentam essas combinações de configuração e as validam com testes completos. As implantações do FlexPod que se desviam dessas configurações são totalmente suportadas se seguirem as diretrizes deste documento e se todos os componentes estiverem listados como compatíveis na Lista de compatibilidade de hardware e software do Cisco UCS e no NetApp http://mysupport.netapp.com/matrix["IMT"^] .

Por exemplo, a adição de mais controladores de storage ou servidores Cisco UCS e a atualização de software para versões mais recentes serão totalmente compatíveis se o software, o hardware e as configurações atenderem às diretrizes definidas neste documento.
