---
sidebar: sidebar 
permalink: fp-def/dc-tech-spec_minimum_hardware_requirements.html 
keywords: minimum, hardware, requirements, switches, fabric, interconnects, servers, storage, controllers 
summary: Uma configuração de data center do FlexPod tem requisitos mínimos de hardware, incluindo, entre outros, switches, interconexões de malha, servidores e controladores de storage NetApp. 
---
= Requisitos mínimos de hardware
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Uma configuração de data center do FlexPod tem requisitos mínimos de hardware, incluindo, entre outros, switches, interconexões de malha, servidores e controladores de storage NetApp.

Uma configuração do FlexPod tem os seguintes requisitos mínimos de hardware:

* Dois switches Cisco Nexus em configuração redundante. Essa configuração pode consistir em dois switches redundantes da série Cisco Nexus 9000 mencionada anteriormente. Os dois switches devem ser do mesmo modelo e configurados no mesmo modo de operação.



NOTE: Se você estiver implementando uma arquitetura ACI, deverá observar os seguintes requisitos adicionais: * Implemente os switches Cisco Nexus série 9000 em uma topologia leaf-spine. * Utilize três Cisco Application Policy Infrastructure Controllers (APICs).

* Dois Cisco UCS 6400, 6500 ou 6600 Series Fabric Interconnects em uma configuração redundante, caso você esteja utilizando os UCS C-Series Rack Servers ou os X-Series Modular systems.
* Dois servidores de rack Cisco UCS Série C com conectividade FI e configuração gerenciada pelo Cisco Intersight (IMM), ou o Cisco UCS Série X Direct com Cisco IMM, ou o Cisco UCS Série X Modular com configuração gerenciada pelo Cisco Intersight (IMM).



NOTE: Se você estiver usando os servidores de rack UCS sem conectividade FI, poderá usar o CIMC ou o modo autônomo do Intersight para gerenciamento.

* Dois controladores NetApp AFF, NetApp ASA ou NetApp FAS em uma configuração de alta disponibilidade (HA) implantados como um cluster de dois nós. Se você estiver usando NetApp AFX, são necessários no mínimo quatro controladores NetApp AFX, que devem ser implantados como um cluster HA de quatro nós, juntamente com um par de switches de interconexão de cluster.
* É necessário, no mínimo, um compartimento para discos NetApp para os controladores de armazenamento que não possuem um compartimento para discos incorporado.

