---
sidebar: sidebar 
permalink: fp-def/dc-tech-spec_cisco_components.html 
keywords: cisco, components, ucs, fabric, interconnect, server, rack, apic, nexus, software, support, mds, x-series-modular, x-series-direct 
summary: A Cisco contribuiu substancialmente para o design e a arquitetura do FlexPod, abrangendo tanto as camadas de computação quanto de rede da solução. Esta seção descreve as opções do Cisco UCS e do Cisco Nexus disponíveis para o FlexPod. 
---
= Componentes do Cisco
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Cisco contribuiu substancialmente para o design e a arquitetura do FlexPod, abrangendo tanto as camadas de computação quanto de rede da solução. Esta seção descreve as opções do Cisco UCS, Nexus e MDS disponíveis para o FlexPod.



[[cisco-ucs-fabric-interconnect-options]]
== Opções de interconexão de malha do Cisco UCS

Interconexões de malha redundantes são necessárias na arquitetura do FlexPod. Ao adicionar vários chassis Cisco UCS a um par de interconexões de malha, lembre-se de que o número máximo de chassis em um ambiente é determinado por um limite de arquitetura e de porta.

Os números de peça mostrados na tabela a seguir referem-se às interconexões básicas da malha. Eles não incluem a fonte de alimentação (PSU), os módulos SFP+, QSFP+ ou os módulos de expansão.

|===
| Interconexão de malha Cisco UCS | Número de peça | Especificações técnicas 


| O Cisco UCS 6664 | UCS-FI-6664-U .2+| https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-6600-series-fabric-interconnect-specsheet.pdf["O Cisco UCS 6600 Series Fabric Interconnect"] 


| Cisco UCS 6652 | UCS-FI-6652-U 


| Cisco UCS 6536 | UCSX-FI-6536-U | https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/cisco-ucs-6536-fabric-interconnect-spec-sheet.pdf["Cisco UCS 6536 Fabric Interconnect"] 


| Cisco UCS 6454 | UCS-FI-6454-U .2+| https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-b-series-blade-servers/6400-specsheet.pdf["Cisco UCS série 6400 Fabric Interconnect"] 


| O Cisco UCS 64108 | UCS-FI-64108-U 


| UCS 9108 100G Fabric Interconnect (Cisco UCS X-Series Direct) | UCSX-S9108-100G | https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-fabric-interconnect-9108-100g.pdf["Cisco UCS 9108 Fabric Interconnect"] 
|===


[[cisco-ucs-x-series-chassis-option]]
== Opção de chassi do Cisco UCS X-Series

Para usar os nós de computação do Cisco UCS X-Series, você precisa ter um chassi do Cisco UCS X-Series. A tabela a seguir descreve a opção de chassi do Cisco UCS X-Series.

|===
| Lâmina da série X Cisco UCS | Número de peça | Especificações técnicas 


| Chassis Cisco UCS X9508 | UCSX-9508 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/datasheet-c78-2472574.html?ccid=cc002456&oid=dstcsm026317["Chassis Cisco UCS X9508"] 
|===
Cada chassi do Cisco UCS 9508 deve ter dois módulos de malha inteligentes (IFMs) Cisco UCS 9108 para fornecer conetividade redundante às interconexões de malha.



[[cisco-ucs-x-series-device-options]]
== Opções de dispositivo Cisco UCS X-Series

Os nós de computação do Cisco UCS X-Series estão disponíveis com várias opções de CPU, memória e e/S. Os números de peça listados na tabela a seguir são para o nó base. Eles não incluem CPU, memória, unidades ou placas adaptadoras mezzanine. Várias opções de configuração estão disponíveis e são compatíveis com a arquitetura FlexPod.

|===
| Nós de computação do Cisco UCS X-Series | Número de peça | Especificações técnicas 


| Cisco UCS X210c M7 | UCSX-210C-M7 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x210c-m7-compute-node-ds.html["Nó de computação Cisco UCS X210c M7"] 


| Cisco UCS X210c M8 | UCSX-210C-M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x210c-m8-compute-node-ds.html["Nó de computação Cisco UCS X210c M8"] 


| Cisco UCS X215c M8 | UCSX-215C-M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x215c-m8-compute-node-ds.html["Nó de computação Cisco UCS X215c M8"] 


| Cisco UCS X410c M7 | UCSX-410C-M7 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x410c-m7-compute-node-ds.html["Nó de computação Cisco UCS X410c M7"] 


| Cisco UCS X410c M8 | UCSX-410C-M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x410c-m8-compute-node-ds.html["Nó de computação Cisco UCS X410c M8"] 
|===
A tabela abaixo lista os nós PCI Express disponíveis para o chassi Cisco UCS X-Series.

|===
| Nós PCIe da série Cisco UCS X | Número de peça | Especificações técnicas 


| Cisco UCS X580p PCIe Node | UCSX-580P-U | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x580p-pcie-node-ds.html["Cisco UCS X580p PCIe Node"] 


| Cisco UCS X440p PCIe Node | UCSX-440P | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x440p-pcle-node-ds.html["Cisco UCS X440p PCIe Node"] 
|===
A tabela abaixo lista os módulos X-Fabric disponíveis para o chassi Cisco UCS X-Series.

|===
| Módulos X-Fabric Cisco UCS X-Series | Número de peça | Especificações técnicas 


| Módulo de Fabric Inteligente Cisco UCS 9108 | UCSX-I-9108-100G | https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/cisco-ucs-9108-100g-intelligent-fabric-module-spec-sheet.pdf["Módulo de Fabric Inteligente Cisco UCS 9108"] 


| Módulo Cisco UCS X9516 X-Fabric | UCSX-FS-9516 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-9516-x-fabric-module-ds.html["Módulo Cisco UCS X9516 X-Fabric"] 


| Módulo Cisco UCS X9416 X-Fabric | UCSX-F-9416 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/solution-overview-c22-2432175.html?ccid=cc002456&oid=sowcsm025665["Módulo Cisco UCS X9416 X-Fabric"] 
|===


[[cisco-ucs-x-series-modular-system]]
== O Cisco UCS X-Series Modular System

O sistema modular Cisco UCS X-Series começa com o chassi de servidor Cisco UCS X9508, projetado para ser adaptável e pronto para o futuro. O chassi possui uma malha Ethernet unificada com os módulos Cisco UCS Intelligent Fabric e a tecnologia Cisco UCS X-Fabric para outras tecnologias. Na parte superior traseira do chassi, há dois módulos de malha inteligente que conectam o chassi aos Cisco UCS Fabric Interconnects das séries 6400, 6500 e 6600.

Para uma visão geral rápida dos recursos e funcionalidades da série Cisco UCS X, consulte link:https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x-series-modular-system-aag.html["Visão geral do sistema modular Cisco UCS X-Series"^].

Os nós de computação Cisco UCS X215c M8, Cisco UCS X210c e Cisco UCS X410c oferecem as funcionalidades de servidores blade e rack, proporcionando densidade de computação, capacidade de storage e expansibilidade em um único fator forma.

O nó PCIe Cisco UCS X440p suporta a adição de GPUs com PCIe Gen 4.0 com o módulo Cisco UCS X9416 X-Fabric. O nó PCIe Cisco UCS X580p suporta a adição de GPUs com PCIe Gen 5.0 com o módulo Cisco UCS X9516 X-Fabric.

Consulte as especificações técnicas de cada um desses componentes nas seções acima para obter mais informações sobre os componentes da solução Cisco UCS X-Series Modular System.


NOTE: Consulte o seguinte link para obter as especificações técnicas completas do sistema modular Cisco UCS X-Series: link:https://www.cisco.com/c/en/us/products/servers-unified-computing/ucs-x-series-modular-system/datasheet-listing.html["O Cisco UCS X-Series Modular System"^]



[[cisco-ucs-x-series-direct-options]]
== Opções diretas da série Cisco UCS X

Cisco UCS X-Series Direct é uma nova arquitetura que integra um par de Cisco UCS Fabric Interconnect 9108 100G com Cisco UCS X9508 Chassis e Cisco UCS X-Series Compute nodes para fornecer a solução UCS X-Series Direct.

Para uma visão geral rápida dos recursos e funcionalidades da série Cisco UCS X, consulte link:https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x-series-direct-aag.html["Visão geral do Cisco UCS X-Series Direct"^].

Cisco UCS X-Series Direct é composto pelos seguintes componentes:

* Cisco UCS 9108 100G Fabric Interconnect
* Chassis Cisco UCS X9508
* Cisco UCS X-Series Nós de computação
* Componentes opcionais:
+
** Nós PCIe e módulo X-Fabric
** Segundo chassi Cisco UCS X9508 com nós de computação da série X, módulos de malha inteligente Cisco UCS 9108-100G e até quatro servidores de rack da série C




Consulte as especificações técnicas de cada um desses componentes nas seções acima para obter mais informações sobre os componentes da solução Cisco UCS X-Series Direct.


NOTE: Consulte o seguinte link para obter as especificações técnicas completas do Cisco UCS X-Series Direct: https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x-series-direct-ds.html["Cisco UCS X-Series Folha de dados direta"].



[[cisco-ucs-c-series-rack-server-options]]
== Opções de servidor de rack Cisco UCS Série C

Os servidores de rack Cisco UCS Série C estão disponíveis em versões de uma, duas e quatro unidades de rack (RU), com diversas opções de CPU, memória e E/S. Os números de peça listados na segunda tabela abaixo referem-se ao servidor de base. Eles não incluem CPUs, memória, unidades de disco e placas Peripheral Component Interconnect Express (PCIe). Múltiplas opções de configuração estão disponíveis e são suportadas na arquitetura FlexPod.

A tabela a seguir lista as opções do servidor de rack Cisco UCS C-Series.

|===
| Servidor de rack Cisco UCS Série C Cisco | Número de peça | Especificações técnicas 


| Cisco UCS C220 M7 | UCSC-C220-M7 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c220-m7-rack-server-ds.html["Servidor Rack Cisco UCS C220 M7"] 


| Cisco UCS C220 M8 | UCSC-C220-M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c220-m8-rack-server-ds.html["Servidor Rack Cisco UCS C220 M8"] 


| Cisco UCS C225 M8 | UCSC-C225-M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c225-m8-rack-server-ds.html["Servidor Rack Cisco UCS C225 M8"] 


| Cisco UCS C240 M7 | UCSC-C240-M7 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c240-m7-rack-server-ds.html["Servidor Rack Cisco UCS C240 M7"] 


| Cisco UCS C240 M8 | UCSC-C240-M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c240-m8-rack-server-ds.html["Servidor Rack Cisco UCS C240 M8"] 


| Cisco UCS C245 M8 | UCSC-C245-M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c245-m8-rack-server-ds.html["Servidor Rack Cisco UCS C245 M8"] 
|===
A tabela a seguir lista os servidores de rack Cisco UCS Série C otimizados para casos de uso de IA:

|===
| Servidor de rack Cisco UCS C-Series | Número de peça | Especificações técnicas 


| Cisco UCS C845A M8 | UCSC-C845A-M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c845a-m8-rack-server-ds.html["Servidor Rack Cisco UCS C845A M8"] 


| Cisco UCS C880A M8 | UCSC-C880A-M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c880a-m8-rack-server-ds.html["Servidor Rack Cisco UCS C880A M8"] 
|===
As gerações anteriores dos servidores Cisco UCS Série C podem ser usadas na arquitetura FlexPod se forem compatíveis com o  https://ucshcltool.cloudapps.cisco.com/public/["Lista de compatibilidade de hardware e software do Cisco UCS"^].



[[cisco-nexus-9000-series-switch-options]]
== Opções de switch da série Cisco Nexus 9000

Switches redundantes da série Cisco Nexus 9000 são necessários na arquitetura FlexPod. Os números de peça listados na tabela abaixo são referentes ao chassi da série Cisco Nexus 9000; eles não incluem módulos SFP nem módulos Ethernet.

|===
| Cisco Nexus switch - Fixo | Especificações técnicas 


| Cisco Nexus série 9200 switch | https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/datasheet-c78-735989.html["Switches Cisco Nexus 9200 Series"] 


| Cisco Nexus série 9300 switch | https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/datasheet-c78-736967.html["Switches Cisco Nexus 9300 Series"] 
|===
|===
| Switch Cisco Nexus - Modular | Especificações técnicas 


| Cisco Nexus série 9400 switch | https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/nexus9400-series-switches-ds.html?ccid=cc002962&oid=dstdnc029385["Switches Cisco Nexus 9400 Series"] 


| Cisco Nexus série 9500 switch | https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/datasheet-c78-729404.html["Switches Cisco Nexus 9500 Series"] 


| Cisco Nexus série 9800 switch | https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/nexus9800-series-switches-ds.html?ccid=cc002962&oid=dstdnc029386["Switches Cisco Nexus 9800 Series"] 
|===


[[cisco-apic-options]]
== Opções Cisco APIC

Cisco APIC é o principal componente arquitetônico do Cisco ACI. Ele fornece gerenciamento centralizado, controle de políticas e automação para as estruturas Cisco ACI.

Para obter mais informações sobre as especificações do produto APIC, consulte a Tabela 1 até a Tabela 3 no  https://www.cisco.com/c/en/us/products/collateral/cloud-systems-management/application-policy-infrastructure-controller-apic/datasheet-c78-739715.html["Folha de dados do controlador de infraestrutura de políticas de aplicações da Cisco"^].



[[cisco-mds-options]]
== Opções do Cisco MDS

Embora os switches Cisco MDS sejam um elemento opcional da arquitetura FlexPod, as implementações que utilizam conectividade SAN Fibre Channel para acesso ao storage de alto desempenho devem implementar estruturas de switches Cisco MDS redundantes para fornecer uma infraestrutura SAN altamente disponível. A tabela abaixo lista os switches Cisco MDS suportados. Consulte a  https://imt.netapp.com["NetApp IMT"^] e a  https://ucshcltool.cloudapps.cisco.com/public/["Lista de compatibilidade de hardware e software do Cisco"^] para obter uma lista completa dos switches SAN suportados.

|===
| Switch Cisco MDS | Descrição 


| Switches de malha multicamadas Cisco MDS 9100 | http://www.cisco.com/c/en/us/products/storage-networking/mds-9100-series-multilayer-fabric-switches/datasheet-listing.html["Switches Cisco MDS série 9100"] 


| Switches multisserviços Cisco MDS 9200 | https://www.cisco.com/c/en/us/products/storage-networking/mds-9200-series-multiservice-switches/datasheet-listing.html["Switches Cisco MDS 9200 Series"] 


| Switches de malha multicamadas Cisco MDS 9300 Cisco | https://www.cisco.com/c/en/us/products/storage-networking/mds-9300-series-multilayer-fabric-switches/datasheet-listing.html["Switches Cisco MDS série 9300"] 


| Os Cisco MDS 9700 Multilayer Directors | http://www.cisco.com/c/en/us/products/storage-networking/mds-9700-series-multilayer-directors/datasheet-listing.html["Switches Cisco MDS série 9700"] 
|===


[[cisco-support-licensing-options]]
== Opções de licenciamento de suporte do Cisco


NOTE: Recomenda-se confirmar os requisitos de licenciamento com seu representante de vendas da Cisco ou da NetApp antes de fazer o pedido.

link:https://www.cisco.com/c/dam/en_us/about/doing_business/legal/service_descriptions/docs/solution-support-smart-total-care.pdf["Suporte a Soluções Cisco"^]É uma oferta de serviço de suporte técnico que se aplica às soluções da Cisco que incluem tanto hardware quanto software apenas da Cisco ou da Cisco e dos Solution Support Alliance Partners, e são compostas exclusivamente por produtos da Cisco e produtos fornecidos por fornecedores terceirizados (Solution Support Alliance Partner(s)).

Cisco oferece suporte a ambientes complexos de clientes por meio de seu link:https://www.cisco.com/c/en/us/support/web/tac/technical-services-resource-guide.html["Centro de Assistência Técnica"]. O Cisco Solution Support garante ao cliente acesso a uma equipe de engenheiros do TAC, que atuam como ponto de contato principal para problemas encontrados na solução, além de fornecer suporte para o hardware e o software que a compõem.

A Cisco utiliza a link:https://www.tsanet.org/cisco-tsanet-case-study/["Programa de Parceiros TSANet"^] estrutura para integrar os Parceiros de Suporte a Soluções em um grupo privado no sistema TSANet Connect. O TSANet Connect oferece um método consistente para que os Engenheiros de Suporte colaborem com as equipes técnicas dos Parceiros, garantindo uma comunicação eficiente e uma resolução de problemas mais ágil, sem o atrito causado por esforços informais para trabalhar com os parceiros.
