---
sidebar: sidebar 
permalink: fp-def/dc-tech-spec_power_and_cabling_requirements.html 
keywords: power, cabling, requirements, flexpod, datacenter, netapp, cisco, ucs, disk shelves 
summary: Esta seção descreve os requisitos de energia e as diretrizes de cabeamento para racks de discos em um FlexPod Datacenter. 
---
= Diretrizes de energia e cabeamento
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Esta seção descreve os requisitos de energia e as diretrizes de cabeamento para um projeto FlexPod Datacenter.



[[power-requirements]]
== Requisitos de energia

Os requisitos de energia para o data center FlexPod diferem com base no local onde a configuração do data center FlexPod está instalada.

Para obter mais dados sobre a potência máxima necessária e para obter outras informações detalhadas sobre a energia, consulte as especificações técnicas de cada componente de hardware listado na link:dc-tech-spec_technical_specifications_and_references.html["Especificações técnicas e Referências: Componentes de hardware"]seção .

Para obter dados detalhados sobre o consumo de energia do Cisco UCS, consulte o  https://ucspowercalculator.cisco.com/["Calculadora de energia Cisco UCS"^].

Para dados de alimentação do controlador de armazenamento da NetApp, consulte a  https://hwu.netapp.com/["NetApp Hardware Universe"^]. Em *Plataformas*, selecione a plataforma de storage que você deseja usar (por exemplo, AFF A90), selecione a versão do ONTAP e clique em *Mostrar Resultados*. Os dados do cabo de alimentação estão listados na seção *Cabos de Alimentação Compatíveis*. Para detalhes sobre tamanho, peso, potência etc., consulte a seção *Tamanho, Peso, Acústica, Alimentação*.



[[cabling-guidelines]]
== Diretrizes de cabeamento

Esta seção fornece diretrizes gerais de cabeamento para um projeto FlexPod Datacenter.

* Garanta conectividade redundante para as conexões de computação e storage.
* A velocidade das conexões precisa ser compatível com os componentes conectados.
* Consulte a seção link:https://docs.netapp.com/us-en/flexpod/fp-def/dc-tech-spec_topologies.html["FlexPod Datacenter topologias"^] para obter diretrizes adicionais de cabeamento para topologias específicas.


A tabela a seguir fornece diretrizes de cabeamento para NetApp disk shelves que podem ser usados em um projeto FlexPod Datacenter.

|===


| Compartimento de disco | Diretrizes de cabeamento 


| DS212C .3+| link:https://docs.netapp.com/us-en/ontap-systems/sas3/install-cabling-rules.html#configuration-rules["Regras de cabeamento SAS"^] 


| DS224C 


| DS460C 


| NS224 .3+| link:https://docs.netapp.com/us-en/ontap-systems/drive-shelves/index.html["Requisitos e melhores práticas para os shelves NS224 e NX224"^] 


| NS224 com NSM100B 


| NX224 
|===