---
sidebar: sidebar 
permalink: fp-def/dc-tech-spec_netapp_ontap.html 
keywords: ontap, aff, asa, fas, afx, system, datacenter, technical, specifications, flexpod, software 
summary: O software NetApp ONTAP está instalado em todos os sistemas NetApp AFF, ASA, FAS e AFX. O FlexPod é validado com o software ONTAP, proporcionando uma arquitetura de storage dimensionável que permite operações sem interrupções, atualizações sem interrupções e uma infraestrutura de dados ágil. 
---
= NetApp ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
O software NetApp ONTAP é o sistema operacional que roda nos sistemas de armazenamento AFF, ASA, FAS e AFX. O ONTAP oferece uma arquitetura de storage dimensionável altamente escalável que permite operações sem interrupções, upgrades sem interrupções e uma infraestrutura de dados ágil. Com o modelo de licenciamento ONTAP One, todos os serviços de dados corporativos estão incluídos em um único pacote, simplificando a implantação e o gerenciamento, enquanto proporciona acesso completo a recursos avançados. O ONTAP oferece proteção robusta de dados por meio de tecnologias como o SnapMirror para replicação e recuperação de desastres, assim como o SnapCenter para backup e restauração consistentes de aplicações. Ele também incorpora recursos de segurança incorporados, incluindo a Proteção Autônoma contra Ransomware e criptografia, para proteger seus dados contra ameaças modernas. Além disso, o ONTAP permite integração perfeita com nuvem híbrida, com recursos como o SnapMirror Cloud e replicação baseada em S3, possibilitando mobilidade de dados entre ambientes locais e em nuvem, mantendo a consistência e o controle.

Para obter mais informações sobre o ONTAP, consulte a  https://www.netapp.com/ontap-data-management-software/["Software de gerenciamento de dados ONTAP"^]página do produto.
