---
sidebar: sidebar 
permalink: fp-def/dc-tech-spec_connectivity_requirements.html 
keywords: connectivity, requirements, cisco, ucs, fabric, interconnect, uplink, direct, san 
summary: Listados abaixo estão os requisitos de conetividade para a configuração do FlexPod. 
---
= Requisitos de conetividade
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Uma configuração do FlexPod tem os seguintes requisitos de conetividade:

* É necessária uma rede de gerenciamento fora da banda Ethernet de 1 Gb separada para todos os componentes.
* A NetApp recomenda que você habilite o suporte a quadros jumbo em todo o ambiente, mas isso não é necessário.
* As portas de appliance Cisco UCS Fabric Interconnect independentes são recomendadas apenas para conexões iSCSI. Quando conexões NAS são usadas com portas de appliance, switches ethernet Cisco Nexus ou equivalentes adicionais são necessários para determinados cenários de falha.
* Nenhum equipamento adicional pode ser colocado em linha entre os componentes principais do FlexPod.


Ligações uplink:

* As portas nos controladores de armazenamento NetApp devem ser conectadas aos switches Cisco Nexus 9000 Series.
* vPCs são necessários dos switches Cisco Nexus da série 9000 até os controladores de storage NetApp.
* Os vPCs são necessários dos switches Cisco Nexus 9000 Series para as interconexões de malha.
* Um mínimo de duas conexões são necessárias para uma VPC. O número de conexões em uma VPC pode ser aumentado com base na carga do aplicativo e nos requisitos de desempenho.


Ligações diretas:

* As portas do controlador de armazenamento NetApp que estão diretamente conectadas às interconexões de malha (como no caso do X-Series Direct) podem ser agrupadas para habilitar um canal de porta. O vPC não é compatível com essa configuração.
* Os canais de porta FCoE são recomendados para designs FCoE de ponta a ponta.


Inicialização SAN:

* As soluções FlexPod são projetadas em torno de uma arquitetura de inicialização SAN usando protocolos iSCSI, FC ou FCoE. O uso das tecnologias boot-from-SAN fornece a configuração mais flexível para a infraestrutura do data center e permite os recursos avançados disponíveis em cada componente da infraestrutura. Embora a inicialização a partir de SAN seja a configuração mais eficiente, a inicialização a partir de armazenamento de servidor local é uma configuração válida e suportada.
* O boot SAN via FC-NVMe não é suportado.


Consulte a seção link:https://docs.netapp.com/us-en/flexpod/fp-def/dc-tech-spec_topologies.html["FlexPod Datacenter topologias"^] referente aos requisitos de conectividade específicos para cada topologia.
