---
sidebar: sidebar 
permalink: fp-def/dc-tech-spec_solution_overview.html 
keywords: flexpod, datacenter, technical specifications, platform, architecture 
summary: 'A plataforma FlexPod é uma arquitetura de data center pré-projetada e baseada em melhores práticas, construída sobre o Cisco Unified Computing System (Cisco UCS), a família de switches Cisco Nexus e os controladores de armazenamento NetApp (NetApp AFF, ASA, FAS ou sistemas AFX).' 
---
= Especificações técnicas do data center FlexPod
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
A plataforma FlexPod é uma arquitetura de data center pré-projetada, baseada nas melhores práticas, construída sobre o Cisco Unified Computing System (Cisco UCS), a família de switches Cisco Nexus e MDS (para FC) e os controladores de armazenamento NetApp (AFF, ASA, FAS ou AFX).

O FlexPod é uma plataforma adequada para executar uma variedade de hipervisores de virtualização, sistemas operacionais bare-metal, ambientes conteinerizados e cargas de trabalho corporativas. O FlexPod oferece não apenas uma configuração de linha de base, mas também a flexibilidade para ser dimensionado e otimizado para acomodar muitos casos de uso e requisitos diferentes.


NOTE: Antes de encomendar uma configuração completa do FlexPod, consulte a  http://www.netapp.com/us/technology/flexpod["NetApp FlexPod Página inicial"^] para a versão mais recente destas especificações técnicas.

link:dc-tech-spec_flexpod_platforms.html["Próximo: Plataformas FlexPod."]
