---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec_connectivity_requirements.html 
keywords: connectivity, requirements, flexpod, express, aff, fas, asa 
summary: Esta seção descreve os requisitos de conetividade para as diferentes versões do FlexPod Express. 
---
= Requisitos de conetividade
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Esta seção descreve os requisitos gerais de conectividade para as diferentes versões do FlexPod Express.



== Requisitos de conectividade para FlexPod Express com NetApp AFF/ ASA/ FAS

Os requisitos de conectividade para FlexPod Express com NetApp AFF/ ASA/ FAS geralmente incluem:

* NetApp controladores de storage devem ser conectados diretamente aos switches Cisco Nexus.
* Para implementações do Cisco UCS X-Series Direct, os controladores de storage NetApp podem ser conectados diretamente aos Fabric Interconnects integrados.
* Nenhum equipamento adicional pode ser colocado em linha entre os componentes principais do FlexPod.
* Os canais de porta virtuais (vPCs) são necessários para conectar os switches Cisco Nexus 9000 aos controladores de storage NetApp.
* Embora não seja necessário, a ativação do suporte de quadros jumbo é recomendada em todo o ambiente.


Consulte a seção link:https://docs.netapp.com/us-en/flexpod/fp-def/fp-express-tech-spec_flexpod_express_topologies.html["FlexPod topologias Express"^] referente aos requisitos de conectividade específicos para cada topologia.
