---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec__netapp_components.html 
keywords: storage, controller, options, fas, aff, asa, disk, shelves, licensing, software 
summary: NetApp storage controllers fornecem a base de storage na arquitetura FlexPod Express, tanto para boot quanto para storage de dados de aplicações. Esta seção lista as diferentes opções de storage NetApp na arquitetura FlexPod Express. 
---
= Componentes do NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Os controladores de storage do NetApp fornecem a base de storage na arquitetura do FlexPod Express para inicialização e storage de dados de aplicações. Esta seção lista as diferentes opções do NetApp na arquitetura do FlexPod Express.



== Opções do controlador de storage NetApp

Controladores redundantes das séries AFF, ASA ou FAS são necessários na arquitetura FlexPod Express. Os controladores executam o software ONTAP. Ao encomendar os controladores de storage, a versão de software preferida pode ser pré-carregada nos controladores. Para ONTAP, o cluster pode ser implementado com um par de switches de interconexão de cluster ou em uma configuração de cluster sem switch.


NOTE: Uma configuração de cluster sem switch é suportada apenas para uma configuração de dois nós. Switches de interconexão de cluster são necessários para configurações com mais de 4 nós e opcionais para uma configuração de dois nós.

Diferentes opções e configurações estão disponíveis dependendo da plataforma de storage selecionada. Consulte seu representante de vendas para obter detalhes sobre esses componentes adicionais.

As famílias de controladoras listadas na tabela abaixo são adequadas para uso em uma solução FlexPod, pois sua conexão com os switches Cisco Nexus é perfeita. Consulte a  http://hwu.netapp.com/["NetApp Hardware Universe"^] para obter detalhes específicos de compatibilidade para cada modelo de controladora.

|===
| NetApp Família de armazenamento básico para FlexPod Express | Modelo | Especificações técnicas 


.2+| AFF Série A. | A20 .2+| https://www.netapp.com/pdf.html?item=/media/7828-ds-3582-aff-a-series-ai-era.pdf["Documentação da série A do AFF"] 


| A30 


| AFF C-Series | C30 | https://www.netapp.com/pdf.html?item=/media/81583-ds-4240-aff-c-series.pdf["Documentação da Série C AFF"] 


.2+| ASA A-Series | A20 .2+| https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["Documentação da Série A da ASA"] 


| A30 


| ASA C-Series | C30 | https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["Documentação da Série C da ASA"] 


.2+| FAS | FAS 2750 .2+| https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["Documentação FAS"] 


| FAS 2820 
|===


== Discos e compartimentos de disco NetApp

É necessário, no mínimo, um compartimento para discos NetApp para os controladores de armazenamento.

O tipo de compartimento NetApp selecionado determina quais tipos de unidade estão disponíveis nesse compartimento.


NOTE: Para todos os compartimentos de disco e números de peça de disco, consulte o seu representante de vendas.

Para obter mais informações sobre as unidades suportadas, clique no link NetApp Hardware Universe na tabela a seguir e selecione unidades suportadas.

A tabela a seguir lista as opções do compartimento de disco NetApp, juntamente com as unidades compatíveis com cada tipo de compartimento, que podem ser encontradas no NetApp Hardware Universe. Siga o link Hardware Universe, selecione a versão do ONTAP que você está usando e, em seguida, selecione o tipo de prateleira. Na imagem do compartimento, clique em unidades compatíveis para ver as unidades compatíveis com versões específicas do ONTAP e das gavetas de disco.

|===
| Compartimento de disco | Especificações técnicas 


| DS212C .5+| https://hwu.netapp.com/DetailViews/Home.aspx["Compartimentos de disco e Mídia de armazenamento unidades com suporte no NetApp Hardware Universe"] 


| DS224C 


| DS460C 


| NS224 


| NS224 com NSM100B 
|===


== Opções de licenciamento do software NetApp

A tabela a seguir lista as opções de licenciamento de software da NetApp.

|===
| Licenciamento de software da NetApp | Especificações técnicas 


| ONTAP One ou ONTAP base para AFF e FAS .2+| Consulte sua equipe de vendas da NetApp para obter mais informações sobre licenciamento. 


| ONTAP One para SAN para ASA 
|===


== Opções de licenciamento do suporte da NetApp

As licenças SupportEdge Premium são necessárias e os números de peça dessas licenças variam de acordo com as opções selecionadas no design do FlexPod Express.

A tabela a seguir lista as opções de licenciamento de suporte da NetApp para os sistemas de armazenamento NetApp AFF, ASA e FAS.

|===
| Licenciamento do suporte da NetApp | Número de peça | Especificações técnicas 


| SupportEdge Premium4 horas no local; meses: 36 | CS-O2-4HR | link:https://www.netapp.com/pdf.html?item=/media/19784-ds-3873.pdf["https://www.netapp.com/pdf.html?item=/media/19784-ds-3873.pdf"] 
|===