---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec_power_and_cabling_requirements.html 
keywords: power, cabling, requirements, flexpod, express, cisco, ucs, cabling 
summary: Esta seção descreve os requisitos de energia e as diretrizes de cabeamento das gavetas de discos para um projeto FlexPod Express. 
---
= Diretrizes de energia e cabeamento
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Esta seção descreve os requisitos de energia e as diretrizes de cabeamento para um projeto FlexPod Express.



[[power-requirements]]
== Requisitos de energia

Os requisitos de energia para FlexPod Express variam de acordo com o local onde a configuração do FlexPod Express está instalada.

Para obter mais dados sobre a potência máxima necessária e outras informações detalhadas sobre o consumo de energia, consulte a link:https://docs.netapp.com/us-en/flexpod/fp-def/fp-express-tech-spec_technical_specifications_and_references.html["especificações técnicas"^] para cada componente de hardware.

Para obter dados de energia detalhados do Cisco UCS, consulte http://www.cisco.com/assets/cdc_content_elements/flash/dataCenter/cisco_ucs_power_calculator/["Calculadora de energia Cisco UCS"^].

Para obter dados de energia do controlador de armazenamento NetApp, consulte a  http://hwu.netapp.com/Controller/Index?platformTypeId=6780858["NetApp Hardware Universe"^]. Em *Plataformas*, selecione a plataforma de storage que você deseja usar (por exemplo, AFF A20), selecione a versão do ONTAP e clique em *Mostrar Resultados*. Os dados do cabo de alimentação estão listados na seção *Cabos de Alimentação Compatíveis* e, para detalhes sobre tamanho, peso, potência etc., consulte a seção *Tamanho, Peso, Acústica, Alimentação*.



[[cabling-guidelines]]
== Diretrizes de cabeamento

Esta seção fornece diretrizes gerais de cabeamento para um projeto FlexPod Express.

* Garanta conectividade redundante para as conexões de computação e storage.
* A velocidade das conexões precisa ser compatível com os componentes conectados.
* Consulte a seção link:https://docs.netapp.com/us-en/flexpod/fp-def/fp-express-tech-spec_flexpod_express_topologies.html["FlexPod topologias Express"^] para obter diretrizes adicionais de cabeamento para topologias específicas.


A tabela a seguir fornece diretrizes de cabeamento para NetApp disk shelves que podem ser usadas em um FlexPod Express design.

|===


| Compartimento de disco | Diretrizes de cabeamento 


| DS212C .3+| link:https://docs.netapp.com/us-en/ontap-systems/sas3/install-cabling-rules.html#configuration-rules["Regras de cabeamento SAS"^] 


| DS224C 


| DS460C 


| NS224 .2+| link:https://docs.netapp.com/us-en/ontap-systems/drive-shelves/index.html["Requisitos e melhores práticas para shelf NS224"^] 


| NS224 com NSM100B 
|===