---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec_netapp_components.html 
keywords: storage, controller, options, fas, aff, asa, disk, shelves, licensing, software 
summary: NetApp storage controllers fornecem a base de storage na arquitetura FlexPod Express, tanto para boot quanto para storage de dados de aplicações. Esta seção lista as diferentes opções de storage NetApp na arquitetura FlexPod Express. 
---
= Componentes do NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Os controladores de storage do NetApp fornecem a base de storage na arquitetura do FlexPod Express para inicialização e storage de dados de aplicações. Esta seção lista as diferentes opções do NetApp na arquitetura do FlexPod Express.



[[netapp-storage-controller-options]]
== Opções do controlador de storage NetApp

Controladores redundantes das séries AFF, ASA ou FAS são necessários na arquitetura FlexPod Express. Os controladores executam o software ONTAP. Ao encomendar os controladores de storage, a versão de software preferida pode ser pré-carregada nos controladores. Para ONTAP, o cluster pode ser implementado com um par de switches de interconexão de cluster ou em uma configuração de cluster sem switch.


NOTE: Uma configuração de cluster sem switch é suportada apenas para uma configuração com dois nós. Os switches de interconexão de cluster são necessários para configurações com 4 ou mais nós e são opcionais para uma configuração com dois nós.

Diferentes opções e configurações estão disponíveis com base na plataforma de storage selecionada. Consulte seu representante de vendas para obter detalhes sobre esses componentes adicionais.

As famílias de controladoras listadas na tabela abaixo são adequadas para uso em uma solução FlexPod, pois sua conexão com os switches Cisco Nexus é perfeita. Consulte a  http://hwu.netapp.com/["NetApp Hardware Universe"^] para obter detalhes específicos de compatibilidade para cada modelo de controladora.

|===
| NetApp Família de armazenamento básico para FlexPod Express | Modelo | Especificações técnicas 


.2+| AFF Série A. | A20 .2+| https://www.netapp.com/pdf.html?item=/media/7828-ds-3582-aff-a-series-ai-era.pdf["Documentação da série A do AFF"] 


| A30 


| AFF C-Series | C30 | https://www.netapp.com/pdf.html?item=/media/81583-ds-4240-aff-c-series.pdf["Documentação da Série C da AFF"] 


.2+| ASA A-Series | A20 .3+| https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["Documentação ASA"] 


| A30 


| ASA C-Series | C30 


.3+| FAS | FAS 2750 .3+| https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["Documentação FAS"] 


| FAS 2820 


| FAS 50 
|===


[[netapp-disk-shelves-and-disks]]
== Discos e compartimentos de disco NetApp

É necessário, no mínimo, um compartimento para discos NetApp para os controladores de armazenamento que não possuem um compartimento para discos incorporado. O tipo de compartimento NetApp selecionado determina quais tipos de unidades estão disponíveis nesse compartimento.


NOTE: Para todos os compartimentos de disco e números de peça de disco, consulte o seu representante de vendas.

A tabela a seguir lista as opções de gaveta de discos NetApp para FlexPod Express, juntamente com links para suas especificações técnicas.

Para obter a lista de unidades compatíveis com seu disk shelf, acesse link:https://hwu.netapp.com/DetailViews/Home.aspx["NetApp Hardware Universe"^], em *Products > Storage > Shelves* selecione *ONTAP (AFF, ASA, FAS)*, selecione a versão do ONTAP que você está usando, depois selecione o tipo de shelf (exemplo: *DS212C*) e clique em *Show Results*. Clique em *Supported Drives* para ver as unidades compatíveis com versões específicas do ONTAP e os disk shelves.

|===
| Compartimento de disco | Especificações técnicas 


| DS212C .5+| https://www.netapp.com/data-storage/disk-shelves-storage-media/["Prateleiras de discos e mídias de armazenamento"] 


| DS224C 


| DS460C 


| NS224 


| NS224 com NSM100B 
|===


[[netapp-software-licensing-options]]
== Opções de licenciamento do software NetApp

A tabela a seguir lista as opções de licenciamento de software da NetApp.

|===
| Licenciamento de software da NetApp | Especificações técnicas 


| ONTAP One para AFF e FAS .2+| Consulte sua equipe de vendas da NetApp para obter mais informações sobre licenciamento. 


| ONTAP One para SAN para ASA 
|===
Consulte este link para obter mais informações sobre o licenciamento de software da NetApp: https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["Licenciamento de software da NetApp"^].



[[netapp-support-licensing-options]]
== Opções de licenciamento do suporte da NetApp

As licenças SupportEdge Premium são necessárias e os números de peça dessas licenças variam de acordo com as opções selecionadas no design do FlexPod Express.

A tabela a seguir lista as opções de licenciamento de suporte da NetApp para os sistemas de armazenamento NetApp AFF, ASA e FAS.

|===
| Licenciamento do suporte da NetApp | Especificações técnicas 


| NetApp SupportEdge | https://www.netapp.com/netapp-services/[] 
|===