---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec_storage_software.html 
keywords: storage, software, flexpod, express, ontap, e, series, santricity 
summary: Os sistemas operacionais de storage listados nesta seção são compatíveis com a plataforma FlexPod Express. 
---
= Software de storage
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
FlexPod Express é compatível com sistemas de storage que executam os sistemas operacionais NetApp ONTAP ou SANtricity.



== NetApp ONTAP

O NetApp ONTAP é o sistema operacional que roda nos sistemas de storage AFF e FAS. ONTAP oferece uma arquitetura de storage altamente escalável que permite operações sem interrupções, atualizações sem interrupções e uma infraestrutura de dados ágil.

Para obter mais informações sobre o ONTAP, consulte http://www.netapp.com/us/products/platform-os/ontap/index.aspx["Página do produto ONTAP"^].



== Software SANtricity E-Series

O software SANtricity E-Series é o sistema operacional que roda nos sistemas de storage E-Series. SANtricity oferece um sistema altamente flexível que atende a diversas necessidades de aplicações e disponibiliza alta disponibilidade incorporada e uma ampla variedade de recursos de proteção de dados.

Para obter mais informações, consulte o http://www.netapp.com/us/products/platform-os/santricity/index.aspx["Página do produto SANtricity"^].
