---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec_overview.html 
keywords: flexpod, express, technical, specifications, architecture, cisco, ucs 
summary: 'FlexPod Express é uma arquitetura pré-projetada, baseada nas melhores práticas, construída sobre o Cisco Unified Computing System (Cisco UCS) e a família de switches Cisco Nexus, e a camada de storage é construída usando o NetApp FAS ou o NetApp storage E-Series.' 
---
= TR-4293: FlexPod Express Especificações Técnicas
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


Karthick Radhakrishnan, Arvind Ramakrishnan, Lindsey Street, Savita Kumari, NetApp

[role="lead"]
FlexPod Express é uma arquitetura pré-projetada e baseada nas melhores práticas, construída sobre o Cisco Unified Computing System (Cisco UCS) e a família de switches Cisco Nexus, e a camada de storage é construída usando o NetApp FAS ou o storage NetApp E-Series. FlexPod Express é uma plataforma adequada para executar diversos hipervisores de virtualização e sistemas operacionais (SO) bare metal, além de cargas de trabalho corporativas.

FlexPod Express oferece não apenas uma configuração de linha de base, mas também a flexibilidade de ser dimensionado e otimizado para acomodar muitos casos de uso e requisitos diferentes. Este documento categoriza as configurações do FlexPod Express com base no sistema de storage utilizado, FlexPod Express com NetApp FAS e FlexPod Express com E-Series.
