---
sidebar: sidebar 
permalink: fp-def/fp-express-tech-spec_technical_specifications_and_references.html 
keywords: technical, specifications, references, servers, ucs, rack, disk, shelves, aff, asa, fas, x-series-direct, c-series, adapters, controllers 
summary: Esta seção descreve especificações técnicas importantes adicionais para cada um dos componentes do FlexPod Express. 
---
= Especificações técnicas e Referências
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


[role="lead"]
Esta seção descreve especificações técnicas importantes adicionais para cada um dos componentes do FlexPod Express.



== Cisco UCS X-Series Direct chassi

As especificações técnicas do Cisco UCS X-Series Direct chassi, conforme mostrado na tabela abaixo, incluem os seguintes componentes:

* Número de unidades de rack
* Número máximo de nós
* Funcionalidade de malha unificada
* Número de compartimentos de e/S para IFMs


|===
| Componente | Cisco UCS X9508 chassi 


| Unidades de rack | 7 


| Número máximo de nós | 8 


| Capazes de malha unificada | Sim 


| Compartimentos de e/S para IFMs | Dois compartimentos para módulos inteligentes de tecido Cisco UCS 9108 (IFMs) 
|===
Para obter mais informações, consulte link:https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/datasheet-c78-2472574.html["Folha de dados do chassi da série X do Cisco UCS X9508"^].



== Nó de computação Cisco UCS X-Series Direct

As especificações técnicas do nó de computação Cisco UCS X-Series incluem os seguintes componentes:

* Número de soquetes do processador
* Suporte do processador
* Capacidade de memória
* Tamanho e velocidade
* Suporte de inicialização SAN
* Número de slots de adaptador mezzanine
* Taxa de transferência máxima de e/S.
* Fator forma
* Número máximo de nós de computação por chassi


Consulte a tabela abaixo para obter as especificações técnicas dos nós de computação Cisco UCS X-Series Direct.

|===


| Componente | Datasheet do Cisco UCS 


| Cisco UCS X210c M7 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x210c-m7-compute-node-ds.html["Nó de computação Cisco UCS X210c M7"] 


| Cisco UCS X210c M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x210c-m8-compute-node-ds.html["Nó de computação Cisco UCS X210c M8"] 


| Cisco UCS X215c M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x215c-m8-compute-node-ds.html["Nó de computação Cisco UCS X215c M8"] 


| Cisco UCS X410c M7 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x410c-m7-compute-node-ds.html["Nó de computação Cisco UCS X410c M7"] 


| Cisco UCS X410c M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-x410c-m8-compute-node-ds.html["Nó de computação Cisco UCS X410c M8"] 
|===


== Interconexões de malha diretas Cisco UCS X-Series

As especificações técnicas dos interconectores de malha Cisco UCS X-Series incluem fator forma, o número total de portas e slots de expansão e a capacidade de throughput. A tabela a seguir ilustra o datasheet do interconector de malha Cisco UCS X-Series.

|===
| Componente | Datasheet do Cisco UCS 


| Cisco UCS 9108 100G Fabric Interconnect | https://www.cisco.com/c/dam/en/us/products/collateral/servers-unified-computing/ucs-x-series-modular-system/ucs-fabric-interconnect-9108-100g.pdf["Cisco UCS 9108 100G Fabric Interconnect"] 
|===


== Servidores de rack Cisco UCS C-Series

As especificações técnicas dos servidores rack Cisco UCS Série C incluem suporte a processadores, capacidade máxima de memória, número de slots PCIe e fator forma. Para obter mais detalhes sobre os modelos de servidor UCS compatíveis, consulte a  https://ucshcltool.cloudapps.cisco.com/public/["Compatibilidade de hardware do Cisco"^] lista. A tabela a seguir ilustra os datasheets dos servidores rack Série C.

|===
| Componente | Datasheet do Cisco UCS 


| Cisco UCS C220 M7 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c220-m7-rack-server-ds.html["Servidor Rack Cisco UCS C220 M7"] 


| Cisco UCS C220 M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c220-m8-rack-server-ds.html["Servidor Rack Cisco UCS C220 M8"] 


| Cisco UCS C225 M6 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c225-m6-sff-rack-server-ds.html["Servidor de rack Cisco UCS C225 M6"] 


| Cisco UCS C240 M7 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c240-m7-rack-server-ds.html["Servidor Rack Cisco UCS C240 M7"] 


| Cisco UCS C240 M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c240-m8-rack-server-ds.html["Servidor Rack Cisco UCS C240 M8"] 


| Cisco UCS C245 M6 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c245-m6-sff-rack-server-ds.html["Servidor de rack Cisco UCS C245 M6"] 


| Cisco UCS C245 M8 | https://www.cisco.com/c/en/us/products/collateral/servers-unified-computing/ucs-c-series-rack-servers/ucs-c245-m8-rack-server-ds.html["Servidor Rack Cisco UCS C245 M8"] 
|===


== Switches Cisco Nexus

As especificações técnicas dos switches Cisco Nexus estão contidas no datasheet de cada modelo. As especificações incluem o fator forma, o número de supervisores, módulos de malha e slots para placas de linha, além do número máximo de portas. Esses datasheets podem ser encontrados na tabela a seguir.

|===
| Componente | Datasheet do Cisco Nexus 


| Cisco Série Nexus 9200 | https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/datasheet-c78-735989.html["Switches Cisco Nexus 9200 Series"] 


| Cisco Série Nexus 9300 | https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/datasheet-c78-736967.html["Switches Cisco Nexus 9300 Series"] 
|===


== Controladores de storage NetApp

As especificações técnicas dos controladores de armazenamento NetApp incluem a configuração da plataforma, capacidade bruta, memória, fator forma, requisitos da versão do ONTAP, compartimentos de discos, etc.



=== NetApp AFF Série A.

Controladores de armazenamento AFF Série A de nível básico da NetApp são compatíveis para uso no FlexPod Express. Informações adicionais podem ser encontradas na https://www.netapp.com/pdf.html?item=/media/7828-ds-3582-aff-a-series-ai-era.pdf["Especificações técnicas da série AFF A"^] datasheet e na https://hwu.netapp.com/["NetApp Hardware Universe"^]. Consulte a documentação específica da plataforma listada na tabela a seguir para obter informações detalhadas sobre um modelo AFF específico.

|===
| Componente | Documentação da plataforma de controlador AFF A-Series 


| NetApp AFF A20 | https://docs.netapp.com/us-en/ontap-systems/a20-30-50/a20-key-specifications.html#aff-a20-specifications-at-a-glance["Especificações principais do AFF A20"] 


| NetApp AFF A30 | https://docs.netapp.com/us-en/ontap-systems/a20-30-50/a30-key-specifications.html#aff-a30-specifications-at-a-glance["Especificações principais do AFF A30"] 
|===


=== NetApp AFF C-Series

Os controladores de armazenamento AFF Série C de nível básico da NetApp são compatíveis para uso no FlexPod Express. Informações adicionais podem ser encontradas na https://www.netapp.com/pdf.html?item=/media/81583-ds-4240-aff-c-series.pdf["Especificações técnicas da AFF C-Series"^] datasheet e na https://hwu.netapp.com/["NetApp Hardware Universe"^]. Consulte a documentação específica da plataforma listada na tabela a seguir para obter informações detalhadas sobre um modelo AFF específico.

|===
| Componente | Documentação da plataforma de controladores AFF C-Series 


| NetApp AFF C30 | https://docs.netapp.com/us-en/ontap-systems/c30-60/c30-key-specifications.html["Especificações principais do AFF C30"] 
|===


=== NetApp ASA A-Series

Os modelos de entrada dos controladores de armazenamento NetApp ASA A-Series são compatíveis para uso no FlexPod Express. Informações adicionais podem ser encontradas na https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["NetApp ASA Especificações técnicas da série ASA A"^] datasheet e na https://hwu.netapp.com/["NetApp Hardware Universe"^]. Consulte a documentação específica da plataforma listada na tabela a seguir para obter informações detalhadas sobre um modelo ASA específico.

|===
| Componente | NetApp Documentação da plataforma de controladores ASA A-Series 


| NetApp ASA A20 | https://docs.netapp.com/us-en/ontap-systems/asa-r2-key-specifications/asa-a20-key-specifications.html["Especificações principais do ASA A20"] 


| NetApp ASA A30 | https://docs.netapp.com/us-en/ontap-systems/asa-r2-key-specifications/asa-a30-key-specifications.html["Especificações principais do ASA A30"] 
|===


=== NetApp ASA C-Series

Os modelos de entrada dos controladores de armazenamento NetApp ASA C-Series são compatíveis para uso no FlexPod Express. Informações adicionais podem ser encontradas na https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["NetApp ASA C-Series Especificações técnicas"^] datasheet e na https://hwu.netapp.com/["NetApp Hardware Universe"^]. Consulte a documentação específica da plataforma listada na tabela a seguir para obter informações detalhadas sobre um modelo ASA específico.

|===
| Componente | NetApp Documentação da plataforma de controladores ASA C-Series 


| NetApp ASA C30 | https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["Especificações principais do ASA C30"] 
|===


=== Série NetApp FAS

Os controladores de armazenamento FAS de nível básico são compatíveis para uso em um FlexPod Express. As especificações detalhadas de todos os controladores de armazenamento da série FAS estão disponíveis na  https://hwu.netapp.com/["NetApp Hardware Universe"^]. Consulte a documentação específica da plataforma listada na tabela a seguir para obter informações detalhadas sobre um modelo FAS específico.

|===
| Componente | Documentação da plataforma do controlador da série FAS 


| Série FAS2750 | https://docs.netapp.com/us-en/ontap-systems/fas2700/overview.html["FAS2750 Especificações principais"^] 


| Série FAS2820 | https://docs.netapp.com/us-en/ontap-systems/fas2800/overview.html["Especificações principais do FAS2820"^] 
|===


=== Compartimentos de disco NetApp

As especificações técnicas para NetApp gabinetes de discos incluem o fator forma, o número de unidades por gabinete e os módulos de E/S do gabinete; esta documentação pode ser encontrada na tabela a seguir. Para mais informações, consulte a https://hwu.netapp.com/["NetApp Hardware Universe"^].

|===
| Componente | Documentação do compartimento de disco NetApp FAS/AFF 


| Compartimento de disco NetApp DS212C | https://www.netapp.com/data-storage/disk-shelves-storage-media/["DS212C Documentação do compartimento de disco"] 


| Compartimento de disco NetApp DS224C | https://www.netapp.com/data-storage/disk-shelves-storage-media/["DS224C Documentação do compartimento de disco"] 


| Compartimento de disco NetApp DS460C | https://www.netapp.com/data-storage/disk-shelves-storage-media/["DS460C Documentação do compartimento de disco"] 


| NetApp NS224 Prateleira de discos | https://www.netapp.com/data-storage/disk-shelves-storage-media/["NS224 Documentação do compartimento de disco"] 


| NS224 com shelf de disco NSM 100B | https://www.netapp.com/data-storage/disk-shelves-storage-media/["Documentação do NS224 com shelf de disco NSM 100B"] 
|===


=== Unidades NetApp

As especificações técnicas das unidades NetApp incluem o tamanho do fator forma, a capacidade do disco, as RPM do disco, as controladoras compatíveis e os requisitos de versão do ONTAP. Essas especificações podem ser encontradas na seção unidades do http://hwu.netapp.com/Drives/Index?queryId=1581392["NetApp Hardware Universe"^].
