---
sidebar: sidebar 
permalink: hybrid-cloud/fhc-cvoe-where-to-find-additional-information.html 
keywords:  
summary:  
---
= Onde encontrar informações adicionais
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:fhc-cvoe-conclusion.html["Anterior: Conclusão."]

[role="lead"]
Para saber mais sobre as informações descritas neste documento, consulte os seguintes documentos e/ou sites:

* Página inicial do FlexPod
+
https://www.flexpod.com["https://www.flexpod.com"^]

* Cisco validou guias de design e implantação para FlexPod
+
https://www.cisco.com/c/en/us/solutions/design-zone/data-center-design-guides/flexpod-design-guides.html["https://www.cisco.com/c/en/us/solutions/design-zone/data-center-design-guides/flexpod-design-guides.html"^]

* NetApp Console
+
https://console.netapp.com/["https://console.netapp.com/"^]

* NetApp Cloud Volumes ONTAP
+
https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-overview-cvo.html["https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-overview-cvo.html"^]

* Início rápido do Cloud Volumes ONTAP na AWS
+
https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-aws.html["https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-aws.html"^]

* Replicação do SnapMirror
+
https://docs.netapp.com/us-en/cloud-manager-replication/concept-replication.html["https://docs.netapp.com/us-en/cloud-manager-replication/concept-replication.html"^]

* TR-3928: Práticas recomendadas da NetApp para a Epic
+
https://www.netapp.com/pdf.html?item=/media/17137-tr3928pdf.pdf["https://www.netapp.com/pdf.html?item=/media/17137-tr3928pdf.pdf"^]

* TR-4693: Guia de implantação do FlexPod Datacenter para EPIC EHR
+
https://www.netapp.com/media/10658-tr-4693.pdf["https://www.netapp.com/media/10658-tr-4693.pdf"^]

* FlexPod para Epic
+
https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_xseries_vmw_epic.html["https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_xseries_vmw_epic.html"^]

* Ferramenta de Matriz de interoperabilidade do NetApp
+
http://support.netapp.com/matrix/["http://support.netapp.com/matrix/"^]

* Ferramenta de interoperabilidade de hardware e software Cisco UCS
+
http://www.cisco.com/web/techdoc/ucs/interoperability/matrix/matrix.html["http://www.cisco.com/web/techdoc/ucs/interoperability/matrix/matrix.html"^]

* Guia de compatibilidade da VMware
+
http://www.vmware.com/resources/compatibility/search.php["http://www.vmware.com/resources/compatibility/search.php"^]





== Histórico de versões

|===
| Versão | Data | Histórico de versões do documento 


| Versão 1,0 | Março de 2023 | Versão inicial 
|===