---
sidebar: sidebar 
permalink: hybrid-cloud/fpd-ibn-cloud-design.html 
keywords: cisco, flexpod, ibm, data, center, cloud, private, storage 
summary: 'O IBM Cloud Private (ICP) é uma plataforma local para desenvolver e gerenciar aplicativos em contêiner para casos de uso nativos da nuvem e de modernização de aplicativos' 
---
= FlexPod Datacenter com IBM Cloud Private
:allow-uri-read: 


Cisco, NetApp

[role="lead"]
O IBM Cloud Private (ICP) é uma plataforma local para desenvolver e gerenciar aplicativos em contêiner para casos de uso nativos da nuvem e de modernização de aplicativos. Ele é um ambiente integrado desenvolvido com o Kubernetes como sua orquestração de contêineres e inclui um repositório de imagens privado para contentores Docker, um console de gerenciamento, uma estrutura de monitoramento, muitos aplicativos em contêiner IBM e baseados em código aberto e muito mais. Combinar ICP com FlexPod, a infraestrutura convergente da Cisco e NetApp, pode simplificar a implantação e o gerenciamento de sua infraestrutura. Você também pode se beneficiar de eficiência de storage aprimorada, melhor proteção de dados, menor risco e flexibilidade para escalar esse stack de infraestrutura de nível empresarial altamente disponível para acomodar novos requisitos de negócios e outras alterações ao longo do tempo.

link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_icp_ucsm32.html["FlexPod Datacenter com IBM Cloud Private"^]
