---
sidebar: sidebar 
permalink: hybrid-cloud/gcp-ncvo-conclusion.html 
keywords: conclusion 
summary: Nessa solução, o serviço de dados de nuvem NetApp, o Cloud Volumes ONTAP e a infraestrutura de data center FlexPod foram usados para criar uma solução de recuperação de desastres com uma nuvem pública habilitada pelo orquestrador de nuvem Cisco Intersight. A solução FlexPod evoluiu constantemente para permitir que os clientes modernizem seus processos de entrega de aplicações e negócios. Com essa solução, você pode criar um plano BCDR com a nuvem pública como local de destino para um plano de DR transitório ou em tempo integral, mantendo o custo da solução de DR baixo. 
---
= Conclusão
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:gcp-ncvo-solution-validation.html["Anterior: Validação da solução."]

[role="lead"]
Nessa solução, o serviço de dados de nuvem NetApp, o Cloud Volumes ONTAP e a infraestrutura de data center FlexPod foram usados para criar uma solução de recuperação de desastres com uma nuvem pública habilitada pelo orquestrador de nuvem Cisco Intersight. A solução FlexPod evoluiu constantemente para permitir que os clientes modernizem seus processos de entrega de aplicações e negócios. Com essa solução, você pode criar um plano BCDR com a nuvem pública como local de destino para um plano de DR transitório ou em tempo integral, mantendo o custo da solução de DR baixo.

A replicação de dados entre o FlexPod no local e o NetApp Cloud Volumes ONTAP foi feita com tecnologia comprovada da SnapMirror, mas você também pode selecionar outras ferramentas de transferência e sincronização de dados do NetApp, como o Cloud Sync, para seus requisitos de mobilidade de dados. Segurança dos dados em trânsito fornecida pelas tecnologias de criptografia incorporadas baseadas em TLS/AES.

Não importa se você tem um plano de recuperação de desastres temporário para um aplicativo ou um plano de recuperação de desastres em tempo integral para uma empresa, o portfólio de produtos usados nessa solução pode atender a ambos os requisitos em escala. Equipado com o Cisco Intersight Workflow Orchestrator, o mesmo pode ser automatizado com fluxos de trabalho pré-criados que não apenas eliminam a necessidade de reconstruir processos, mas também aceleram a implementação de um plano BCDR.

A solução possibilita o gerenciamento do FlexPod no local e a replicação de dados em uma nuvem híbrida de maneira muito fácil e conveniente, com automação e orquestração oferecidas pelo Cisco Intersight Cloud Orchestrator.



== Onde encontrar informações adicionais

Para saber mais sobre as informações descritas neste documento, consulte os seguintes documentos e/ou sites:



=== GitHub

* Todas as configurações do Terraform usadas
+
https://github.com/ucs-compute-solutions/cvo_snapmirror["https://github.com/ucs-compute-solutions/cvo_snapmirror"^]

* Arquivos JSON para importação de fluxos de trabalho
+
https://github.com/ucs-compute-solutions/FlexPod_DR_Workflows["https://github.com/ucs-compute-solutions/FlexPod_DR_Workflows"^]





=== Cisco Intersight

* Centro de Ajuda do Cisco Intersight
+
https://intersight.com/help/saas/home["https://intersight.com/help/saas/home"^]

* Documentação do Cisco Intersight Cloud Orchestrator:
+
https://intersight.com/help/appliance/orchestration/configure["https://intersight.com/help/appliance/orchestration/configure"^]

* Serviço de Intersight da Cisco para Documentação Terraform da HashiCorp
+
https://community.cisco.com/t5/data-center-and-cloud-knowledge-base/intersight-service-for-terraform/ta-p/4301093["https://community.cisco.com/t5/data-center-and-cloud-knowledge-base/intersight-service-for-terraform/ta-p/4301093"^]

* Folha de dados de Intersight da Cisco
+
https://www.cisco.com/c/en/us/products/collateral/cloud-systems-management/intersight/intersight-ds.html["https://www.cisco.com/c/en/us/products/collateral/cloud-systems-management/intersight/intersight-ds.html"^]

* Folha de dados do Cisco Intersight Cloud Orchestrator
+
https://www.cisco.com/c/en/us/products/collateral/cloud-systems-management/intersight/nb-06-intersight-cloud-orch-aag-cte-en.html["https://www.cisco.com/c/en/us/products/collateral/cloud-systems-management/intersight/nb-06-intersight-cloud-orch-aag-cte-en.html"^]

* Cisco Intersight Service para HashiCorp Terraform Folha de dados
+
https://www.cisco.com/c/en/us/products/collateral/cloud-systems-management/intersight/nb-06-intersight-terraf-ser-aag-cte-en.html["https://www.cisco.com/c/en/us/products/collateral/cloud-systems-management/intersight/nb-06-intersight-terraf-ser-aag-cte-en.html"^]





=== FlexPod

* Página inicial do FlexPod
+
https://www.flexpod.com["https://www.flexpod.com"^]

* Cisco validou guias de design e implantação para FlexPod
+
https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_m6_esxi7u2_design.html["FlexPod Datacenter com Cisco UCS 4,2(1) no modo gerenciado UCS, VMware vSphere 7,0 U2 e NetApp ONTAP 9.9 Guia de Design"^]

* Data center FlexPod com Cisco UCS X-Series
+
https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_xseries_esxi7u2_design.html["https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_xseries_esxi7u2_design.html"^]





=== Interoperabilidade

* Ferramenta de Matriz de interoperabilidade do NetApp
+
http://mysupport.netapp.com/matrix["http://mysupport.netapp.com/matrix"^]

* Ferramenta de interoperabilidade de hardware e software Cisco UCS
+
http://www.cisco.com/web/techdoc/ucs/interoperability/matrix/matrix.html["http://www.cisco.com/web/techdoc/ucs/interoperability/matrix/matrix.html"^]

* Guia de compatibilidade da VMware
+
http://www.vmware.com/resources/compatibility/search.php["http://www.vmware.com/resources/compatibility/search.php"^]





=== Documentos de referência do NetApp Cloud Volumes ONTAP

* NetApp Console Documentação:
+
https://docs.netapp.com/us-en/console-family/index.html["https://docs.netapp.com/us-en/console-family/index.html"^]

* Cloud Volumes ONTAP
+
https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-getting-started-gcp.html[]

* Calculadora de TCO do Google Cloud com NetApp Cloud Volumes ONTAP
+
https://www.netapp.com/google-cloud/google-cloud-calculator/[]

* Dimensionamento e estimativa de custos do Cloud Volumes ONTAP:
+
https://www.netapp.com/ontap-cloud/pricing/["https://www.netapp.com/ontap-cloud/pricing/"^]

* Avaliação da nuvem e análise de infraestrutura:
+
https://docs.netapp.com/us-en/data-infrastructure-insights/[]

* NetApp Soluções de nuvem híbrida:
+
https://www.netapp.com/hybrid-cloud/[]

* Documentação da API do Cloud Manager
+
https://docs.netapp.com/us-en/occm/reference_infrastructure_as_code.html["https://docs.netapp.com/us-en/occm/reference_infrastructure_as_code.html"^]





=== Solução de problemas

https://kb.netapp.com/Cloud/ncds/nds/cvo/cvo_kbs["https://kb.netapp.com/Cloud/ncds/nds/cvo/cvo_kbs"^]



=== Terraform

* Terraform Cloud
+
https://www.terraform.io/cloud["https://www.terraform.io/cloud"^]

* Documentação do Terraform
+
https://www.terraform.io/docs/["https://www.terraform.io/docs/"^]

* Registro do NetApp Cloud Manager
+
https://registry.terraform.io/providers/NetApp/netapp-cloudmanager/lates["https://registry.terraform.io/providers/NetApp/netapp-cloudmanager/lates"^]





=== GCP

* Alta disponibilidade do ONTAP para GCP
+
https://bluexp.netapp.com/blog/gcp-cvo-blg-what-makes-cloud-volumes-ontap-high-availability-for-gcp-tick["https://bluexp.netapp.com/blog/gcp-cvo-blg-what-makes-cloud-volumes-ontap-high-availability-for-gcp-tick"^]

* GCP perquisite
+
https://netapp.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=f3d0368b-7165-4d43-a76e-ae01011853d6["https://netapp.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=f3d0368b-7165-4d43-a76e-ae01011853d6"^]


