---
sidebar: sidebar 
permalink: vdi/fpd-vmw-horiz.html 
keywords: flexpod, cisco, ucs, aff, a300, ontap, data, vmware, vsphere, horizon 
summary: Este documento fornece uma arquitetura de referência e um guia de design para uma carga de trabalho de desktop de 5000 a 6000 lugares, ambiente de computação de usuário final no FlexPod Datacenter com o Cisco UCS e o software de gerenciamento de dados NetApp AFF A300 e NetApp ONTAP. 
---
= FlexPod Datacenter com VMware Horizon View, VMware vSphere 6,7 U2, Cisco UCS Manager 4,0 e NetApp ONTAP 9 7,10 para até 6700 assentos
:allow-uri-read: 


Vadim Lebedev, Cisco Suresh Toppay, NetApp

[role="lead"]
Este documento fornece uma arquitetura de referência e um guia de design para uma carga de trabalho de desktop de 5000 a 6000 lugares, ambiente de computação de usuário final no FlexPod Datacenter com o Cisco UCS e o software de gerenciamento de dados NetApp AFF A300 e NetApp ONTAP. A solução inclui sessões RDS Windows Server 2019 baseadas no servidor VMware Horizon, desktops virtuais Microsoft Windows 10 de clone completo persistente do VMware Horizon e desktops virtuais do Microsoft Windows 10 não persistentes e de clone instantâneo do VMware Horizon no VMware vSphere 6.7U2

link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_ontap96_vmware710_67_u2_ucs_40_6700_seats.html["FlexPod Datacenter com VMware Horizon View, VMware vSphere 6,7 U2, Cisco UCS Manager 4,0 e NetApp ONTAP 9 7,10 para até 6700 assentos"^]
