---
sidebar: sidebar 
permalink: flexpod-dc/fpd-mcc-vsphere-deploy.html 
keywords: flexpod, cisco, data, center, aci, multi-pod, mcc, ip, vmware, vsphere, deployment 
summary: A Cisco e a NetApp fizeram uma parceria para fornecer uma série de soluções FlexPod que permitem plataformas estratégicas de data center. 
---
= FlexPod Datacenter com Cisco ACI multipod com NetApp MetroCluster IP e VMware vSphere 6,7 - implantação
:allow-uri-read: 


Cisco, Cisco Ramesh Issac, Ramesh Issac, Ramakrishnan, NetApp

[role="lead"]
A Cisco e a NetApp fizeram uma parceria para fornecer uma série de soluções FlexPod que permitem plataformas estratégicas de data center. A solução FlexPod oferece uma arquitetura integrada que incorpora as melhores práticas de design para computação, armazenamento e rede, minimizando assim os riscos DE TI validando a arquitetura integrada para garantir a compatibilidade entre vários componentes. A solução também aborda os pontos problemáticos DA TI, fornecendo orientação de projeto documentada, orientação de implantação e suporte que podem ser usados em várias etapas (Planejamento, projeto e implementação) de uma implantação.

link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_esxi67_n9k_aci_metrocluster.html["FlexPod Datacenter com Cisco ACI multipod com NetApp MetroCluster IP e VMware vSphere 6,7 - implantação"^]
