---
sidebar: sidebar 
permalink: flexpod-dc/fpd-vxlan-design.html 
keywords: flexpod, cisco, vmware, data, center, vsphere, vxlan, ontap, cloud, public 
summary: 'Os Cisco Validated designs (CVDs) consistem em sistemas e soluções projetados, testados e documentados para facilitar e melhorar as implantações dos clientes.' 
---
= Data center do FlexPod com VMware vSphere 7,0, Cisco VXLAN Single-Site Fabric e NetApp ONTAP 9.7 - Desenho
:allow-uri-read: 


Ramesh Isaac, Cisco Abhinav Singh, NetApp

[role="lead"]
Os Cisco Validated designs (CVDs) consistem em sistemas e soluções projetados, testados e documentados para facilitar e melhorar as implantações dos clientes. Esses designs incorporam uma ampla gama de tecnologias e produtos em um portfólio de soluções que foram desenvolvidas para atender às necessidades de negócios dos clientes. A Cisco e a NetApp fizeram uma parceria para fornecer o FlexPod, que serve de base para uma variedade de workloads e fornecem designs de arquitetura robustos, eficientes e dimensionáveis para atender aos requisitos do cliente. Uma solução FlexPod é uma abordagem validada para implantar tecnologias e produtos Cisco e NetApp para criar uma infraestrutura compartilhada de nuvem pública e privada.

link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_esxi70_vxlan_evpn_design.html["Data center do FlexPod com VMware vSphere 7,0, Cisco VXLAN Single-Site Fabric e NetApp ONTAP 9.7 - Desenho"^]
