---
sidebar: sidebar 
permalink: flexpod-dc/fpd-vsphere-deploy.html 
keywords: cisco, flexpod, data, center, vmware, vsphere, ontap, deployment 
summary: 'Este documento descreve o data center Cisco e NetApp FlexPod com o NetApp ONTAP 9.7 no sistema de armazenamento all-flash NetApp AFF A400, o software unificado do Cisco UCS Manager versão 4,1(2) com processadores escaláveis Intel Xeon de segunda geração e VMware vSphere 7,0.' 
---
= FlexPod Datacenter com VMware vSphere 7,0 e NetApp ONTAP 9 .7 - implantação
:allow-uri-read: 


João Jorge, Cisco Sree Lakshmi Lanca, NetApp

[role="lead"]
Este documento descreve o data center Cisco e NetApp FlexPod com o NetApp ONTAP 9.7 no sistema de armazenamento all-flash NetApp AFF A400, o software unificado do Cisco UCS Manager versão 4,1(2) com processadores escaláveis Intel Xeon de segunda geração e VMware vSphere 7,0. O Cisco UCS Manager (UCSM) 4,1(2) fornece suporte consolidado do seguinte:

* Todos os modelos atuais de interconexão de tecido Cisco UCS: 6200, 6300, 6324 (Cisco UCS Mini)
* 6400
* Série 2200/2300/2400 IOM
* Cisco UCS B-Series
* Cisco UCS C-Series


Também estão incluídas as plataformas de gerenciamento Cisco Intersight e NetApp Active IQ SaaS.

O FlexPod Datacenter com NetApp ONTAP 9.7, o software unificado Cisco UCS versão(2) e o VMware vSphere 7,0 incluem uma arquitetura de data center pré-projetada e de práticas recomendadas, desenvolvida com base no sistema de computação unificada da Cisco (Cisco UCS), a família de switches Cisco Nexus 9000, switches de malha multicamadas MDS 9000 e arrays de storage NetApp AFF A-Series que executam o software de gerenciamento de dados ONTAP 9.4,1.

link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/fp_vmware_vsphere_7_0_ontap_9_7.html["FlexPod Datacenter com VMware vSphere 7,0 e NetApp ONTAP 9 .7 - implantação"^]
