---
sidebar: sidebar 
permalink: security/flexpod-fips-flexpod-cisco-ucs-compute-and-fips-140-2.html 
keywords: compute, cisco, nist, compliance mode, fabric interconnect, fi, advanced malware protection 
summary: Uma arquitetura FlexPod pode ser projetada com um servidor Cisco UCS compatível com FIPS 140-2-2. De acordo com o NIST dos EUA, o servidor Cisco UCS pode operar no modo de conformidade FIPS 140-2 nível 1. 
---
= Computação do FlexPod Cisco UCS e FIPS 140-2-2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./../media/


link:flexpod-fips-control-plane-versus-data-plane.html["Anterior: Plano de controle versus plano de dados."]

[role="lead"]
Uma arquitetura FlexPod pode ser projetada com um servidor Cisco UCS compatível com FIPS 140-2-2. De acordo com o NIST dos EUA, o servidor Cisco UCS pode operar no modo de conformidade FIPS 140-2 nível 1. Para obter uma lista completa de componentes Cisco compatíveis com FIPS, https://www.cisco.com/c/en/us/solutions/industries/government/global-government-certifications/fips-140.html?flt0_general-table0=UCSM["Página FIPS 140 da Cisco"^] consulte . O Cisco UCS Manager está validado para FIPS 140-2.



== Cisco UCS e interconexão de malha

O Cisco UCS Manager é implantado e executado a partir das interconexões de malha (FIs) do Cisco.

Para obter mais informações sobre o Cisco UCS e como ativar o FIPS, consulte https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/release/notes/CiscoUCSManager-RN-3-2.html["Documentação do Cisco UCS Manager"^].

Para ativar o modo FIPS na interconexão de malha do Cisco em cada malha A e B, execute os seguintes comandos:

....
fp-health-fabric-A# connect local-mgmt
fp-health-fabric-A(local-mgmt)# enable fips-mode
FIPS mode is enabled
....

NOTE: Para substituir um FI em um cluster no Gerenciador de UCS do Cisco versão 3,2(3) por um FI em uma versão anterior ao Cisco UCS versão 3,2(3), desative o modo FIPS (desative `fips-mode`) no FI existente antes de adicionar o FI de substituição ao cluster. Após a formação do cluster, como parte da inicialização do Cisco UCS Manager, o modo FIPS é ativado automaticamente.

A Cisco oferece os seguintes produtos-chave que podem ser implementados na camada de computação ou aplicação:

* *Proteção avançada contra malware (AMP) da Cisco para endpoints.* Suportada em sistemas operativos Microsoft Windows e Linux, esta solução integra capacidades de prevenção, deteção e resposta. Este software de segurança impede violações, bloqueia malware no ponto de entrada e monitora e analisa continuamente as atividades de arquivo e processo para detetar, conter e corrigir rapidamente ameaças que podem evitar defesas de linha de frente. O componente proteção contra atividades maliciosas (MAP) do AMP monitora continuamente todas as atividades de endpoint e fornece deteção em tempo de execução e bloqueio de comportamento anormal de um programa em execução no endpoint. Por exemplo, quando o comportamento do endpoint indica ransomware, os processos ofensivos são encerrados, impedindo a criptografia do endpoint e interrompendo o ataque.
* * AMP para segurança de e-mail.* Os e-mails se tornaram o principal veículo para espalhar malware e realizar ataques cibernéticos. Em média, cerca de 100 bilhões de e-mails são trocados em um único dia, o que fornece aos invasores um excelente vetor de penetração nos sistemas do usuário. Portanto, é absolutamente essencial defender-se contra esta linha de ataque. AMP analisa e-mails para ameaças como explorações de dia zero e malware furtivo escondido em anexos maliciosos. Ele também usa inteligência de URL líder do setor para combater links maliciosos. Ele oferece aos usuários proteção avançada contra spear phishing, ransomware e outros ataques sofisticados.
* *Sistema de prevenção de intrusão de próxima geração (NGIPS).* O Cisco Firepower NGIPS pode ser implantado como um dispositivo físico no data center ou como um dispositivo virtual no VMware (NGIPSv for VMware). Este sistema de prevenção de intrusão altamente eficaz proporciona um desempenho fiável e um baixo custo total de propriedade. A proteção contra ameaças pode ser expandida com licenças de assinatura opcionais para fornecer AMP, visibilidade e controle de aplicativos e recursos de filtragem de URL. O NGIPS virtualizado inspeciona o tráfego entre máquinas virtuais (VMs) e facilita a implantação e o gerenciamento de soluções NGIPS em locais com recursos limitados, aumentando a proteção para ativos físicos e virtuais.


link:flexpod-fips-flexpod-cisco-networking-and-fips-140-2.html["Próximo: Rede FlexPod Cisco e FIPS 140-2."]
