---
sidebar: sidebar 
permalink: ent-db/fpd-oracle-rac-db.html 
keywords: flexpod, datacenter, oracle, rac, cisco, ucs, aff, mds, deploy 
summary: Os designs validados da Cisco incluem sistemas e soluções que são projetados, testados e documentados para facilitar e melhorar as implantações dos clientes. 
---
= FlexPod Datacenter com bancos de dados Oracle RAC no Cisco UCS e NetApp AFF Série A.
:allow-uri-read: 


Tushar Patel, Cisco Hardikkkumar Vyas, Cisco

[role="lead"]
Os designs validados da Cisco incluem sistemas e soluções que são projetados, testados e documentados para facilitar e melhorar as implantações dos clientes. Esses designs incorporam uma ampla gama de tecnologias e produtos em um portfólio de soluções que foram desenvolvidas para atender às necessidades de negócios dos clientes. A Cisco e a NetApp fizeram uma parceria para fornecer o FlexPod, que serve de base para uma variedade de workloads e permite designs de arquitetura eficientes baseados nos requisitos do cliente. Uma solução FlexPod é uma abordagem validada para implantar as tecnologias Cisco e NetApp como uma infraestrutura de nuvem compartilhada.

O data center FlexPod com o sistema NetApp All Flash AFF é uma plataforma de infraestrutura convergente que combina as melhores tecnologias do Cisco e do NetApp em uma poderosa plataforma convergente para aplicações empresariais. A Cisco e a NetApp trabalham em conjunto com a Oracle para dar suporte aos bancos de dados transacionais e sensíveis ao tempo de resposta mais exigentes exigidos pelos negócios atuais.

Este Cisco Validated Design (CVD) descreve a arquitetura de data center FlexPod de referência usando Cisco UCS e NetApp All Flash AFF Storage para implantar um ambiente de banco de dados Oracle RAC altamente disponível. Este documento mostra a configuração de hardware e software dos componentes envolvidos e os resultados de vários testes. Além disso, este documento oferece orientação de implementação e práticas recomendadas usando servidores de computação UCS Cisco, switches de interconexão de malha Cisco, switches MDS Cisco, switches Cisco Nexus, armazenamento NetApp AFF e banco de dados RAC Oracle.

link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_orc12cr2_affaseries.html["FlexPod Datacenter com bancos de dados Oracle RAC no Cisco UCS e NetApp AFF Série A."^]
