---
sidebar: sidebar 
permalink: ent-db/fpd-oracle-deploy.html 
keywords: flexpod, cisco, design, oracle, rac, data, base, ucs, nvme, fibrechannel, fc 
summary: 'Os Cisco Validated designs (CVDs) consistem em sistemas e soluções projetados, testados e documentados para facilitar e melhorar as implantações dos clientes.' 
---
= FlexPod Datacenter com bancos de dados Oracle 19Cg RAC no Cisco UCS e NetApp AFF com NVMe em Fibre Channel
:allow-uri-read: 


Tushar Patel, Cisco Hardikkkumar Vyas, Cisco

[role="lead"]
Os Cisco Validated designs (CVDs) consistem em sistemas e soluções projetados, testados e documentados para facilitar e melhorar as implantações dos clientes. Este documento CVD descreve a solução Cisco e NetApp FlexPod, que é uma abordagem validada para implantar um ambiente de banco de dados Oracle RAC altamente disponível. A Cisco e a NetApp validaram a arquitetura de referência com vários workloads de banco de dados, como OLTP (processamento transacional on-line) e Data Warehouse no laboratório de data center UCS da Cisco. Este documento mostra a configuração de hardware e software dos componentes envolvidos e os resultados de vários testes. Além disso, o documento oferece uma estrutura para a implementação de bancos de dados do Oracle RAC no NVMe/FC usando o Cisco UCS e o sistema de armazenamento NetApp.

link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_oracle_ucs_m5.html["FlexPod Datacenter com bancos de dados Oracle 19Cg RAC no Cisco UCS e NetApp AFF com NVMe em Fibre Channel"^]
