---
sidebar: sidebar 
permalink: ent-db/fpd-sap-afa-design.html 
keywords: flexpod, cisco, sap, hana, ucs, aff, a-series, tdi 
summary: 'Este documento descreve a solução Cisco e NetApp FlexPod, que é uma abordagem validada para a implantação de ambientes de integração de data centers personalizados (TDI) do SAP HANA.' 
---
= Solução FlexPod Datacenter para SAP com Cisco UCS Manager 4,0 e NetApp AFF A-Series - Design
:allow-uri-read: 


Ramamurthy, Cisco Marco Schoen, NetApp

[role="lead"]
Este documento descreve a solução Cisco e NetApp FlexPod, que é uma abordagem validada para a implantação de ambientes de integração de data centers personalizados (TDI) do SAP HANA. Esse design validado fornece diretrizes e uma estrutura para implementar o SAP HANA com as práticas recomendadas da Cisco e da NetApp.

O FlexPod é uma infraestrutura integrada líder que dá suporte a uma ampla variedade de workloads e casos de uso empresariais. Essa solução permite que você implante o SAP HANA de forma rápida e confiável com um modelo de modo de integração de data center personalizado.

link:https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/UCS_CVDs/flexpod_datacenter_sap_netappaffa_design.html["Solução FlexPod Datacenter para SAP com Cisco UCS Manager 4,0 e NetApp AFF A-Series - Design"^]
